- id: home_mode_away
  alias: Home Mode - Set away when everyone leaves
  description: When everyone leaves And 5 minutes have passed Then the Home Mode switches
    to Away
  trigger:
  - platform: state
    entity_id: group.people
    from: home
    to: not_home
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.home_mode
    data:
      option: Away
  - scene: scene.goodbye
  mode: single
- id: welcome_home
  alias: Welcome Home
  description: 'When someone arrives home: If state is not Sleep, set state to home.
    If it''s after sunset, turn on dining room light and globe lamp.'
  trigger:
  - platform: state
    entity_id: group.people
    to: home
  - platform: state
    entity_id: person.eric
    to: home
  - platform: state
    entity_id: person.nicole
    to: home
  condition: []
  action:
  - choose:
    - conditions:
      - condition: not
        conditions:
        - condition: state
          entity_id: input_select.home_mode
          state: Sleep
      sequence:
      - service: input_select.select_option
        data:
          option: Home
        target:
          entity_id: input_select.home_mode
    - conditions:
      - condition: state
        entity_id: binary_sensor.night
        state: 'on'
      sequence:
      - type: turn_on
        device_id: 96935feeb1e56a473fbcb4b4b4fbfd27
        entity_id: switch.globe_lamp
        domain: switch
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.dining_room_dimmer
      - choose:
        - conditions:
          - condition: time
            before: 06:00:00
            after: 04:00:00
          sequence:
          - service: light.turn_on
            data:
              brightness_pct: 20
            target:
              entity_id: light.eric_office_light
        default: []
    default: []
  mode: single
- id: '1639682032795'
  alias: Scene - Goodnight at 2:00am
  description: When the time is 2:00am And Someone is home Then call the goodnight
    scene
  trigger:
  - platform: time
    at: 02:00
  condition:
  - condition: state
    entity_id: group.people
    state: home
  action:
  - scene: scene.goodnight
  mode: single
- id: '1639704472426'
  alias: Ecobee - Call thermostat script
  description: When the Time of Day or Home Mode changes Then Set the Thermostat
  trigger:
  - platform: state
    entity_id: binary_sensor.day
    to: 'on'
  - platform: state
    entity_id: binary_sensor.dusk
    to: 'on'
  - platform: state
    entity_id: binary_sensor.morning
    to: 'on'
  - platform: state
    entity_id: binary_sensor.night
    to: 'on'
  - platform: state
    entity_id: input_select.home_mode
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: python_script.set_ecobee
    data:
      weather: weather.ecobee_thermostat
      thermostat: climate.ecobee_thermostat
  mode: single
- id: '1640090788072'
  alias: Lighting - Turn lights off at sunrise
  description: When the sun rises Then turn off Outdoor Lights And Turn off the nightlight
  trigger:
  - platform: sun
    event: sunrise
    offset: '0'
  condition: []
  action:
  - type: turn_off
    device_id: 270c91f7718161af4127d8eb00d5cf32
    entity_id: light.nightlight
    domain: light
  - service: light.turn_off
    target:
      area_id: outdoors
  mode: single
- id: '1640110823028'
  alias: Scene - Trigger watch TV when Remote goes from PowerOff after sunset
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: d824906b0d4aea07973580f026dc7ed9
    entity_id: remote.family_room_remote
    domain: remote
  condition:
  - condition: sun
    after: sunset
    after_offset: '-1:00'
  action:
  - scene: scene.watch_tv
  mode: single
- id: '1640264600563'
  alias: Lighting - Turn lights on at sunset
  description: When the sun rises Then turn off Outdoor Lights And Turn off the nightlight
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition: []
  action:
  - service: light.turn_on
    target:
      area_id: outdoors
  - type: turn_on
    device_id: 270c91f7718161af4127d8eb00d5cf32
    entity_id: light.nightlight
    domain: light
  mode: single
- id: '1640269776987'
  alias: Notification - Notify if water detected in basement
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: f1988841f3fd56b85b26e5b1cfcfccab
    entity_id: binary_sensor.hot_water_heater_flood_sensor_any
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_erics_iphone
    data:
      title: Basement Flood Sensor
      message: Water detected in basement.
  - service: notify.mobile_app_nicole_iphone
    data:
      title: Basement Flood Sensor
      message: Water detected in basement.
  mode: single
- id: '1640709513122'
  alias: Nicole Office - Turn on floor lamp with wall switch
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 3b585a2a41b618f9cb095cd55d94ce74
    entity_id: switch.nicole_office_lights
    domain: switch
  condition: []
  action:
  - type: turn_on
    device_id: 84233bfe9142301d0caf5e3ba80fef60
    entity_id: switch.nicole_office_floor_lamp
    domain: switch
  mode: single
- id: '1640709546537'
  alias: Nicole Office - Turn off floor lamp with wall switch
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 3b585a2a41b618f9cb095cd55d94ce74
    entity_id: switch.nicole_office_lights
    domain: switch
  condition: []
  action:
  - type: turn_off
    device_id: 84233bfe9142301d0caf5e3ba80fef60
    entity_id: switch.nicole_office_floor_lamp
    domain: switch
  mode: single
- id: '1640787196947'
  alias: Basement - Control lights with single switch
  description: When the basement light switch is toggled, change the state of the
    other lights to match.
  trigger:
  - platform: device
    type: changed_states
    device_id: c250ce4f0b12576b46fa9e0391822a38
    entity_id: switch.basement_lights
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: c250ce4f0b12576b46fa9e0391822a38
        entity_id: switch.basement_lights
        domain: switch
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          area_id: basement
      - service: light.turn_off
        data: {}
        target:
          area_id: basement
    - conditions:
      - condition: device
        type: is_on
        device_id: c250ce4f0b12576b46fa9e0391822a38
        entity_id: switch.basement_lights
        domain: switch
      sequence:
      - type: turn_on
        device_id: d0bbca2d3726b6419e9cc70b7a95722c
        entity_id: switch.gym_lights
        domain: switch
      - type: turn_on
        device_id: 146e389c8f1db698d76680b08f131e99
        entity_id: light.basement_stairs_light
        domain: light
    default: []
  mode: single
- id: shellies_announce
  alias: HACS - Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: HACS - Shellies Discovery
  trigger:
  - platform: mqtt
    topic: shellies/announce
  action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
  mode: queued
  max: 999
- id: '1640874149023'
  alias: Nicole Office - Turn off lights when no one in office
  description: When no motion is detected in the Office And 5 minutes have passed
    Then turn off the lights
  trigger:
  - type: no_motion
    platform: device
    device_id: aa43c0bccd576d4987586522ab5fa9d3
    entity_id: binary_sensor.nicole_office_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 3b585a2a41b618f9cb095cd55d94ce74
    entity_id: switch.nicole_office_lights
    domain: switch
  mode: single
- id: '1641667112268'
  alias: Basement - Turn on basement lights with motion
  description: When motion is detected in the basement, turn on the lgihts
  trigger:
  - type: motion
    platform: device
    device_id: d1a883d2e796fc27213aadc0aad04a1b
    entity_id: binary_sensor.basement_motion_sensor_0e38cd22_ias_zone
    domain: binary_sensor
  condition:
  - condition: template
    value_template: '{{ (states.switch.basement_lights.last_changed) < (now() - timedelta(
      minutes = 1 ))}}'
  action:
  - type: turn_on
    device_id: c250ce4f0b12576b46fa9e0391822a38
    entity_id: switch.basement_lights
    domain: switch
  mode: single
- id: '1642185258937'
  alias: Nicole Office - Turn on filter workday mornings
  description: ''
  trigger:
  - platform: time
    at: 07:00
  condition:
  - condition: state
    entity_id: binary_sensor.nicole_workday_sensor
    state: 'on'
  action:
  - service: switch.turn_on
    target:
      device_id: a16dc6ccbdc67705acdb84885360d1f8
  mode: single
- id: '1642193400953'
  alias: Nicole Office - Turn off filter after work
  description: ''
  trigger:
  - platform: time
    at: '16:00'
  condition:
  - condition: state
    entity_id: binary_sensor.nicole_workday_sensor
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      device_id: a16dc6ccbdc67705acdb84885360d1f8
  mode: single
- id: '1642209630036'
  alias: Basement - Turn on workbench light with motion
  description: When motion is detected in workbench room turn on the light
  trigger:
  - type: motion
    platform: device
    device_id: 63234ed61d6290fc93bf5153115ba8ef
    entity_id: binary_sensor.basement_workbench_motion_sensor_ias_zone
    domain: binary_sensor
  condition: []
  action:
  - type: turn_on
    device_id: f72754504a3fc7dd7707dcc954348eb5
    entity_id: light.basement_workbench_light
    domain: light
  mode: single
- id: '1648747676385'
  alias: Family Room - Control sub with remote
  description: When the remote turns on, turn on the sub.
  trigger:
  - platform: device
    type: changed_states
    device_id: d824906b0d4aea07973580f026dc7ed9
    entity_id: remote.family_room_remote
    domain: remote
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: d824906b0d4aea07973580f026dc7ed9
        entity_id: remote.family_room_remote
        domain: remote
      sequence:
      - type: turn_on
        device_id: a92e583bc2e9af0c7902a1cf6aca3a3e
        entity_id: switch.family_room_sub
        domain: switch
    - conditions:
      - condition: device
        type: is_off
        device_id: d824906b0d4aea07973580f026dc7ed9
        entity_id: remote.family_room_remote
        domain: remote
      sequence:
      - type: turn_off
        device_id: a92e583bc2e9af0c7902a1cf6aca3a3e
        entity_id: switch.family_room_sub
        domain: switch
    default: []
  mode: single
- id: '1648924822558'
  alias: Notification - Smoke Detector Activated
  description: ''
  trigger:
  - type: problem
    platform: device
    device_id: fe22124a5684619e2af2005c3afc93de
    entity_id: binary_sensor.kitchen_smoke_alarm_smoke_alarm_smoke_alarm_test
    domain: binary_sensor
  - type: co
    platform: device
    device_id: 5dd20b9615b858ea31f5f02431fde004
    entity_id: binary_sensor.basement_smoke_detector_co_alarm_carbon_monoxide_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 5dd20b9615b858ea31f5f02431fde004
    entity_id: binary_sensor.basement_smoke_detector_smoke_alarm_smoke_detected
    domain: binary_sensor
  - type: co
    platform: device
    device_id: ac353f226d5faf78efe8bd287741ea47
    entity_id: binary_sensor.downstairs_smoke_detector_co_alarm_carbon_monoxide_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: ac353f226d5faf78efe8bd287741ea47
    entity_id: binary_sensor.downstairs_smoke_detector_smoke_alarm_smoke_detected
    domain: binary_sensor
  - type: co
    platform: device
    device_id: 5dc7a5753d33064cf1c660f0097e0be2
    entity_id: binary_sensor.upstairs_smoke_detector_co_alarm_carbon_monoxide_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 5dc7a5753d33064cf1c660f0097e0be2
    entity_id: binary_sensor.upstairs_smoke_detector_smoke_alarm_smoke_detected
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: fe22124a5684619e2af2005c3afc93de
    entity_id: binary_sensor.smoke_and_carbon_monoxide_alarm_smoke_alarm_smoke_detected
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_nicole_iphone
    data:
      title: Smoke Detector Activated!
      message: Smoke detector has been activiated.
  - service: notify.mobile_app_erics_iphone
    data:
      message: Smoke detector has been activiated.
      title: Smoke Detector Activated!
  mode: single
- id: '1649549687291'
  alias: Master Bathroom - Humidity Management
  description: ''
  trigger:
  - type: humidity
    platform: device
    device_id: 7ba36598dccd4e9310bf7c044decd042
    entity_id: sensor.master_bathroom_sensor_humidity
    domain: sensor
    below: 56
  - platform: device
    type: turned_on
    device_id: a661b2686aff252c938e2863135cd183
    entity_id: switch.master_bath_fan
    domain: switch
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: a661b2686aff252c938e2863135cd183
    entity_id: switch.master_bath_fan
    domain: switch
  mode: single
- id: '1649768577077'
  alias: Master Bathroom - Turn off lights when no motion detected
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 7ba36598dccd4e9310bf7c044decd042
    entity_id: binary_sensor.master_bathroom_sensor_home_security_motion_detection
    domain: binary_sensor
    for:
      hours: 0
      minutes: 30
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.master_bath_light
  mode: single
- id: '1649768858205'
  alias: Downstairs - Turn off den and family room lights with no motion.
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.den
    to: 'off'
    for:
      hours: 0
      minutes: 40
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      area_id:
      - family_room
      - den
  mode: single
- id: '1649961428008'
  alias: Eric Office - Turn off lights when no one in office
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 964b6a45231edb68895c05eceaeb13bf
    entity_id: binary_sensor.eric_office_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.eric_office_light
  mode: single
- id: '1650396215500'
  alias: Blueprint - Vacation Lighting
  description: ''
  use_blueprint:
    path: vacation_lighting.yaml
    input:
      vacation_mode_toggle: input_boolean.vacation_mode
      default_brightness: 100
      replay_sensor_1: sensor.replay_dining_room_dimmer
      light_target_1: light.dining_room_dimmer
      replay_sensor_2: sensor.replay_basement_lights
      light_target_2: group.basement_lights
      replay_sensor_3: sensor.replay_eric_office_light
      light_target_3: light.eric_office_light
      replay_sensor_4: sensor.replay_family_room_track_light_back
      light_target_4: light.family_room_track_light_back
      replay_sensor_5: sensor.replay_family_room_track_light_front
      light_target_5: light.family_room_track_light_front
      replay_sensor_6: sensor.replay_garage_lights
      light_target_6: group.garage_lights
      replay_sensor_7: sensor.replay_master_bath_fan
      light_target_7: switch.master_bath_fan
      replay_sensor_8: sensor.replay_master_bath_light
      light_target_8: light.master_bath_light
      replay_sensor_9: sensor.replay_nicole_nightstand
      light_target_9: light.nicole_nightstand
      replay_sensor_10: sensor.replay_nicole_office_lights
      light_target_10: group.nicole_office_lights
