# Time of Day
- platform: tod
  name: Day
  after: sunrise
  before: sunset
  before_offset: "-1:00:00"
- platform: tod
  name: Dusk
  after: sunset
  after_offset: "-1:00:00"
  before: sunset
- platform: tod
  name: Night
  after: sunset
  before: sunrise