light:
# MJ Dimmers - These do not work well with Tasmota integration.
- name: "Family Room Track Light - Back"
  state_topic: "stat/FamilyRoom_TrackLight_Back/POWER"
  command_topic: "cmnd/FamilyRoom_TrackLight_Back/POWER"
  availability_topic: "tele/FamilyRoom_TrackLight_Back/LWT"
  brightness_state_topic: "stat/FamilyRoom_TrackLight_Back/RESULT"
  brightness_command_topic: "cmnd/FamilyRoom_TrackLight_Back/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: 807d3a3730e8
- name: "Master Bath Light"
  state_topic: "stat/MB_Bath_Light/POWER"
  command_topic: "cmnd/MB_Bath_Light/POWER"
  availability_topic: "tele/MB_Bath_Light/LWT"
  brightness_state_topic: "stat/MB_Bath_Light/RESULT"
  brightness_command_topic: "cmnd/MB_Bath_Light/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: master_bath_light
- name: "Eric Office Light"
  state_topic: "stat/EricOfficeLight/POWER"
  command_topic: "cmnd/EricOfficeLight/POWER"
  availability_topic: "tele/EricOfficeLight/LWT"
  brightness_state_topic: "stat/EricOfficeLight/RESULT"
  brightness_command_topic: "cmnd/EricOfficeLight/Dimmer"
  brightness_scale: 100
  brightness_value_template: "{{ value_json.Dimmer }}"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: EricOfficeLight
# Shelly Dimmers - Not autodiscoverable
- name: Dining Room Dimmer  
  schema: template
  state_topic: "shellies/shellydimmer2-D8BFC019F016/light/0/status"
  state_template: "{% if value_json.ison %} on {% else %} off {% endif %}"
  command_topic: "shellies/shellydimmer2-D8BFC019F016/light/0/set"
  command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
  command_off_template: '{"turn": "off"}'
  brightness_template: "{{ (value_json.brightness | float * 2.55) | round(0) }}"
  unique_id: dining_room_dimmer
# Workbench LED Light
- name: "Workbench LED Light"
  state_topic: "stat/workbench_led/POWER"
  command_topic: "cmnd/workbench_led/POWER"
  availability_topic: "tele/workbench_led/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  unique_id: workbench_led_light

sensor:
- name: "Energy Bridge"
  icon: mdi:home-lightning-bolt
  state_topic: "event/metering/summation/minute"
  unit_of_measurement: "W"
  value_template: "{{ value_json.value }}"
  state_class: total
  unique_id: energy_bridge
- name: "Energy Bridge - Kwh" #Converts the W vaule int Kwh, for energy dashboard
  icon: mdi:home-lightning-bolt
  state_topic: "event/metering/summation/minute"
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.value | float / 60000 }}"
  last_reset_value_template:  "{{ now().fromtimestamp(value_json.time / 1000).replace(tzinfo=now().tzinfo) }}"
  device_class: energy
  state_class: total
  unique_id: energy_bridge_kwh
