# Discogs
- platform: discogs
  token: !secret discogs_token
  monitored_conditions:
    - collection

# History Stats - Used for vacation lighting
- platform: history_stats
  name: "replay_nicole_office_lights"
  entity_id: light.nicole_office_wall_switch
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_nicole_office_lights
- platform: history_stats
  name: "replay_dining_room_dimmer"
  entity_id: light.dining_room_table_dimmer
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_dining_room_dinner
- platform: history_stats
  name: "replay_eric_office_light"
  entity_id: light.eric_office_light
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_eric_office_light
- platform: history_stats
  name: "replay_family_room_track_light_front"
  entity_id: light.family_room_track_light_front
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_family_room_track_light_front
- platform: history_stats
  name: "replay_kitchenette_spot_lights"
  entity_id: light.kitchenette_spot_lights
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay.kitchenette_spot_lights
- platform: history_stats
  name: "replay_master_bath_light"
  entity_id: light.master_bath_light
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_master_bath_light
- platform: history_stats
  name: "replay_kitchen_overhead_lights"
  entity_id: light.kitchen_overhead_lights
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.kitchen_overhead_lights
- platform: history_stats
  name: "replay_garage_lights"
  entity_id: light.garage_lights_north
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_garage_lights
- platform: history_stats
  name: "replay_basement_lights"
  entity_id: light.basement_lights
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_basement_lights
- platform: history_stats
  name: "replay_living_room_wall_dimmer"
  entity_id: light.living_room_wall_dimmer
  state: "on"
  type: count
  start: >
    {{ as_timestamp(now()) - (7*86400) }}
  duration: 00:00:30
  unique_id: sensor.replay_living_room_wall_dimmer

# Open EVSE
- platform: openevse
  host: 192.168.50.133
  monitored_variables:
    - status
    - charge_time
    - ambient_temp
    - usage_session
    - usage_total