set_ecobee:
  name: Set Ecobee
  description: Sets the Ecobee Operation Mode and Preset based on the home mode, time of day, and forecasted high temperature.
  fields:
    thermostat:
      description: The thermostat to set.
      example: climate.ecobee_thermostat
    weather:
      description: The ecobee weather entitiy to use for getting the high temperature
      example: weather.ecobee_thermostat
