set_ecobee:
  name: Set Ecobee
  description: Sets the Ecobee Operation Mode and Preset based on the home mode, time of day, and forecasted high temperature.
  fields:
    thermostat:
      description: The thermostat to set.
      example: climate.ecobee_thermostat
    weather:
      description: The ecobee weather entitiy to use for getting the high temperature
      example: weather.ecobee_thermostat

set_ecobee_dte_update:
  name: Set Ecobee DTE Update
  description: Sets the Ecobee Operation Mode with Peak Billing
  fields:
    thermostat:
      description: The thermostat to set.
      example: climate.ecobee_thermostat
    weather:
      description: The ecobee weather entitiy to use for getting the high temperature
      example: weather.ecobee_thermostat

set_fr_thermostat:
  name: Set Family Room Thermostat
  description: Sets the Family Room temperature, based off the main thermostat.
  fields:
    main_thermostat:
      description: The thermostat that will set reference temperature.
      example: climate.ecobee_thermostat
    fr_thermostat:
      description: The thermostat to be set.
      example: climate.family_room_thermostat